import React, { useEffect, useState } from 'react';
import { Bar } from 'react-chartjs-2';
import axios from 'axios';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend } from 'chart.js';
import api from '../../axios'
ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

const DoctorsRevenueBarChart: React.FC = () => {
  const [chartData, setChartData] = useState<{ labels: string[]; data: number[] }>({ labels: [], data: [] });

  useEffect(() => {
    const fetchChartData = async () => {
      try {
        const response = await api.get('/admin/getDoctorsRevenueBarChart', { withCredentials: true });
        setChartData(response.data);
      } catch (error) {
        console.error('Error fetching bar chart data:', error);
      }
    };

    fetchChartData();
  }, []);

  const data = {
    labels: chartData.labels,
    datasets: [
      {
        label: 'Revenue (in rupees)',
        data: chartData.data,
        backgroundColor: 'rgba(75, 192, 192, 0.6)',
        borderColor: 'rgba(75, 192, 192, 1)',
        borderWidth: 1,
      },
    ],
  };

  const options = {
    responsive: true,
    plugins: {
      legend: {
        position: 'top' as const,
      },
      title: {
        display: true,
        text: 'Revenue Generated by Doctors',
      },
    },
  };

  return (
    <div>
      <h2 className="text-center"></h2>
      <Bar data={data} options={options} />
    </div>
  );
};

export default DoctorsRevenueBarChart;
